### ISSUE TITLE
[BUG/ERROR] Interim output for `analyze` mode doesn't match description

### ISSUE THREAD

**Issue by forrestdavis** [forrestdavis/NLPScholar#11]
## Describe the bug

The byROI file is stated to  be a  "TSV file with one row for each sentence. The columns are the mean and probability and surprisal aggregated over the ROI for the corresponding sentence." Presently the probability isn't returned and, more importantly, some sentences are dropped. So we are not getting a row for each sentence in a transparent way. I assume there is some aggregation happening over lemmas or conditions. It would be good to minimally surface the sentid so the output could be aligned. This was pointed out to me by @gia-kalro 

## To Reproduce

1. Navigate to NLPScholar
2. Download the following data file [simple_agrmt_all.txt](https://github.com/user-attachments/files/17369986/simple_agrmt_all.txt)
3. Create the following config 

```yaml
exp: MinimalPair

mode:
    - evaluate
    - analyze

models:
        hf_masked_model:
          - bert-large-cased

datafpath: simple_agrmt_all.txt
predfpath: pred_simple_agrmt_all.tsv
resultsfpath: res_simple_agrmt_all.tsv
```
4. Run `main.py`
5. Note that in `res_simple_agrmt_all.tsv` that there is not one row for each sentence

## Expected behavior

Expected one row per sentence 

## Observed behavior 

Missing rows 

## Setup (please complete the following information)
 - OS: macOS
